binary_sensor:
  - platform: homeassistant
    id: ha_floor_light_state
    entity_id: light.floor_light   # placeholder
    on_state:
      - lvgl.widget.update:
          id: lv_floor_light_switch
          state:
            checked: !lambda "return x;"
  - platform: homeassistant
    id: ha_bathroom_light_state
    entity_id: light.bathroom_light   # placeholder
    on_state:
      - lvgl.widget.update:
          id: lv_bathroom_switch
          state:
            checked: !lambda "return x;"
